CREATE TABLE `bigquery-retailrocket.retailrocket_bronze.bronze_item_properties`;
(;
  itemid INT64,;
  property STRING,;
  value STRING,;
  timestamp INT64,;
  timestamp_ms INT64;
);
OPTIONS(;
  description="Bronze item properties: timestamp cast to INT64 (ms)";
);;
CREATE TABLE `bigquery-retailrocket.retailrocket_bronze.bronze_category_tree`;
(;
  categoryid INT64,;
  parentid INT64;
);
OPTIONS(;
  description="Bronze category tree: pass-through from landing";
);;
CREATE TABLE `bigquery-retailrocket.retailrocket_bronze.bronze_events`;
(;
  timestamp INT64,;
  timestamp_ms INT64,;
  event_timestamp TIMESTAMP,;
  visitorid INT64,;
  itemid INT64,;
  event STRING,;
  transactionid INT64;
);
OPTIONS(;
  description="Bronze events: typed, null visitorid/itemid removed";
);;
