CREATE VIEW `bigquery-retailrocket.retailrocket_dataform_assertions.business_logic`;
OPTIONS(;
  description="Business logic checks: event types, date range, transactionid rules";
);
AS SELECT 'event_type_count' AS check_name, CAST(COUNT(*) AS STRING) AS detail;
FROM `bigquery-retailrocket.retailrocket_gold.dim_event_type`;
HAVING COUNT(*) != 3;
;
UNION ALL;
;
SELECT 'event_type_set', STRING_AGG(event_type ORDER BY event_type);
FROM `bigquery-retailrocket.retailrocket_gold.dim_event_type`;
HAVING STRING_AGG(event_type ORDER BY event_type) != 'addtocart,transaction,view';
;
UNION ALL;
;
SELECT 'future_dates', CAST(COUNT(*) AS STRING);
FROM `bigquery-retailrocket.retailrocket_gold.dim_date`;
WHERE full_date > CURRENT_DATE();
HAVING COUNT(*) > 0;
;
UNION ALL;
;
SELECT 'wrong_year', CAST(MIN(EXTRACT(YEAR FROM full_date)) AS STRING);
FROM `bigquery-retailrocket.retailrocket_gold.dim_date`;
HAVING MIN(EXTRACT(YEAR FROM full_date)) != 2015;
;
UNION ALL;
;
SELECT 'dow_out_of_range', CAST(MAX(day_of_week) AS STRING);
FROM `bigquery-retailrocket.retailrocket_gold.dim_date`;
HAVING MAX(day_of_week) > 7 OR MIN(day_of_week) < 1;
;
UNION ALL;
;
SELECT 'quarter_out_of_range', CAST(MAX(quarter) AS STRING);
FROM `bigquery-retailrocket.retailrocket_gold.dim_date`;
HAVING MAX(quarter) > 4 OR MIN(quarter) < 1;
;
UNION ALL;
;
SELECT 'min_events_per_user', CAST(MIN(total_events) AS STRING);
FROM `bigquery-retailrocket.retailrocket_gold.dim_users`;
HAVING MIN(total_events) < 1;
;
UNION ALL;
;
SELECT 'negative_item_ids', CAST(COUNT(*) AS STRING);
FROM `bigquery-retailrocket.retailrocket_gold.dim_items`;
WHERE itemid < 0;
HAVING COUNT(*) > 0;
;
UNION ALL;
;
SELECT 'transactionid_on_nontransaction', CAST(COUNT(*) AS STRING);
FROM `bigquery-retailrocket.retailrocket_gold.fact_events` f;
JOIN `bigquery-retailrocket.retailrocket_gold.dim_event_type` det ON f.event_type_sk = det.event_type_sk;
WHERE det.event_type != 'transaction' AND f.transactionid IS NOT NULL;
HAVING COUNT(*) > 0;;
CREATE VIEW `bigquery-retailrocket.retailrocket_dataform_assertions.referential_integrity`;
OPTIONS(;
  description="No orphan foreign keys in fact_events";
);
AS WITH orphans AS (;
  SELECT COUNT(*) AS orphan_count;
  FROM `bigquery-retailrocket.retailrocket_gold.fact_events` f;
  LEFT JOIN `bigquery-retailrocket.retailrocket_gold.dim_date`       dd ON f.event_date = dd.full_date;
  LEFT JOIN `bigquery-retailrocket.retailrocket_gold.dim_users`      du ON f.user_sk = du.user_sk;
  LEFT JOIN `bigquery-retailrocket.retailrocket_gold.dim_items`      di ON f.item_sk = di.item_sk;
  LEFT JOIN `bigquery-retailrocket.retailrocket_gold.dim_event_type` det ON f.event_type_sk = det.event_type_sk;
  WHERE dd.full_date IS NULL;
     OR du.user_sk IS NULL;
     OR di.item_sk IS NULL;
     OR det.event_type_sk IS NULL;
);
SELECT 'orphan' AS check_name, orphan_count;
FROM orphans;
WHERE orphan_count > 0;;
CREATE VIEW `bigquery-retailrocket.retailrocket_dataform_assertions.unique_keys`;
OPTIONS(;
  description="All primary keys must be unique";
);
AS SELECT;
  'duplicate_pk' AS check_name,;
  table_name,;
  total,;
  distinct_count;
FROM (;
  SELECT 'dim_date' AS table_name, COUNT(*) AS total, COUNT(DISTINCT full_date) AS distinct_count FROM `bigquery-retailrocket.retailrocket_gold.dim_date`;
  UNION ALL;
  SELECT 'dim_users', COUNT(*), COUNT(DISTINCT user_sk) FROM `bigquery-retailrocket.retailrocket_gold.dim_users`;
  UNION ALL;
  SELECT 'dim_items', COUNT(*), COUNT(DISTINCT item_sk) FROM `bigquery-retailrocket.retailrocket_gold.dim_items`;
  UNION ALL;
  SELECT 'dim_categories', COUNT(*), COUNT(DISTINCT category_sk) FROM `bigquery-retailrocket.retailrocket_gold.dim_categories`;
  UNION ALL;
  SELECT 'dim_event_type', COUNT(*), COUNT(DISTINCT event_type_sk) FROM `bigquery-retailrocket.retailrocket_gold.dim_event_type`;
  UNION ALL;
  SELECT 'fact_events', COUNT(*), COUNT(DISTINCT event_sk) FROM `bigquery-retailrocket.retailrocket_gold.fact_events`;
);
WHERE total != distinct_count;;
CREATE VIEW `bigquery-retailrocket.retailrocket_dataform_assertions.row_counts`;
OPTIONS(;
  description="Fact table row count must equal silver events (1:1 grain preserved)";
);
AS SELECT;
  'fact_count_mismatch' AS check_name,;
  fact_count,;
  silver_count;
FROM (SELECT COUNT(*) AS fact_count FROM `bigquery-retailrocket.retailrocket_gold.fact_events`) f;
CROSS JOIN (SELECT COUNT(*) AS silver_count FROM `bigquery-retailrocket.retailrocket_silver.silver_events`) s;
WHERE fact_count != silver_count;;
