CREATE TABLE `bigquery-retailrocket.retailrocket_gold.dim_categories`;
(;
  category_sk INT64,;
  category_id INT64,;
  parent_id INT64;
);
OPTIONS(;
  description="Category dimension with parent hierarchy";
);;
CREATE TABLE `bigquery-retailrocket.retailrocket_gold.fact_events`;
(;
  event_sk INT64,;
  event_date DATE,;
  event_timestamp TIMESTAMP,;
  user_sk INT64,;
  item_sk INT64,;
  event_type_sk INT64,;
  transactionid STRING;
);
PARTITION BY event_date;
CLUSTER BY user_sk, item_sk;
OPTIONS(;
  description="Fact table: one row per user action (view, cart, transaction)";
);;
CREATE TABLE `bigquery-retailrocket.retailrocket_gold.dim_event_type`;
(;
  event_type_sk INT64,;
  event_type STRING;
);
OPTIONS(;
  description="Event type dimension (view, addtocart, transaction)";
);;
CREATE TABLE `bigquery-retailrocket.retailrocket_gold.dim_date`;
(;
  full_date DATE,;
  year INT64,;
  month INT64,;
  day INT64,;
  day_of_week INT64,;
  day_name STRING,;
  is_weekend BOOL,;
  month_name STRING,;
  quarter INT64;
);
OPTIONS(;
  description="Date dimension with calendar attributes";
);;
CREATE TABLE `bigquery-retailrocket.retailrocket_gold.dim_users`;
(;
  user_sk INT64,;
  visitorid INT64,;
  first_event_ts TIMESTAMP,;
  last_event_ts TIMESTAMP,;
  total_events INT64,;
  total_purchases INT64,;
  has_purchased BOOL;
);
OPTIONS(;
  description="User dimension with engagement metrics";
);;
CREATE TABLE `bigquery-retailrocket.retailrocket_gold.dim_items`;
(;
  item_sk INT64,;
  itemid INT64,;
  category_sk INT64,;
  is_available INT64;
);
OPTIONS(;
  description="Item dimension with category and availability (SCD Type 1)";
);;
