CREATE TABLE `bigquery-retailrocket.retailrocket_landing.item properties`;
(;
  timestamp INT64,;
  itemid INT64,;
  property STRING,;
  value STRING;
);;
CREATE TABLE `bigquery-retailrocket.retailrocket_landing.events`;
(;
  timestamp INT64,;
  visitorid INT64,;
  event STRING,;
  itemid INT64,;
  transactionid INT64;
);;
CREATE TABLE `bigquery-retailrocket.retailrocket_landing.category tree`;
(;
  categoryid INT64,;
  parentid INT64;
);;
