CREATE TABLE `bigquery-retailrocket.retailrocket_silver.silver_item_properties`;
(;
  itemid INT64,;
  property STRING,;
  value STRING,;
  timestamp_ms INT64;
);
OPTIONS(;
  description="Silver item properties: filtered to categoryid/available, deduped on (itemid, property, timestamp_ms)";
);;
CREATE TABLE `bigquery-retailrocket.retailrocket_silver.silver_events`;
(;
  timestamp INT64,;
  timestamp_ms INT64,;
  event_timestamp TIMESTAMP,;
  visitorid INT64,;
  itemid INT64,;
  event STRING,;
  transactionid INT64;
);
OPTIONS(;
  description="Silver events: deduped on (timestamp_ms, visitorid, itemid, event)";
);;
CREATE TABLE `bigquery-retailrocket.retailrocket_silver.silver_category_tree`;
(;
  categoryid INT64,;
  parentid INT64;
);
OPTIONS(;
  description="Silver category tree: pass-through from bronze";
);;
